################################################################
# redis service and a subscriber service
################################################################
name: redisapp
services:
  redis:
    image: redis:8.0
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      # Viya information
      - REDIS_PORT=6379
      - REDIS_HOST=localhost
      - REDIS_SSL=false
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_AOF_ENABLED=no
  subscriber:
    build: ./subscriber
    container_name: subscriber
    volumes: 
      - ~/.sas:/usr/src/app/.sas
    environment:
      - REDIS_CHANNEL=score
      - CAS_TABLE=cancerscores
      - CAS_LIB=Public
      - DEBUG=
      